### ISSUE TITLE
Show hostname instead of IP

### ISSUE THREAD

**Issue by clemisch** [MegaManSec/SSH-Snake#8]
Is there a way to show the hostname instead of the IP in the printout, and ultimately the visualization? 

One could do a lookup retroactively of course, but if the script is running on the hosts anyway...

Sorry if there already is an option and I missed it.

**Comment by MegaManSec** [comment]
There's a fundamental issue with doing this: if a host does not have bash installed or some error is encountered, it's going to print the IP address of the host because that's all the calling host knows (A->B, if B fails for some reason, A will print the ip address used to connect to B) -- see all of the "exceptional" errors here: https://github.com/MegaManSec/SSH-Snake/blob/main/OUTPUT.md

However, if you do really want to do this, you can either:

1. Change https://github.com/MegaManSec/SSH-Snake/blob/main/Snake.sh#L732 to `hostnames_chain="$hostnames_chain${hostnames_chain:+->}$user@("$(hostname"))"`
2. Use [custom_cmds](https://github.com/MegaManSec/SSH-Snake/blob/main/SETTINGS.md#custom_cmds) to print the values.`custom_cmds=('echo $hostnames_chain${hostnames_chain:+->}$user@("$(hostname)")')` may work (untested, but if it does work, please let me know). You'd then have to filter out these values from the output and run the python script with just those values.

**Comment by MegaManSec** [comment]
`custom_cmds=('echo "$hostnames_chain${hostnames_chain:+->}$user@("$(hostname)")"')` works, but then you need to modify the python script:

```
diff --git a/tools/generate-graph.py b/tools/generate-graph.py
index 48d4480..c969ff5 100755
--- a/tools/generate-graph.py
+++ b/tools/generate-graph.py
@@ -19,10 +19,10 @@ def build_lookup_table(input_lines, ignore_dest_user, dot):
         line = line.strip()
         line = re.sub(r"^\[?\d+\]?\s*", "", line)
 
-        if ": " in line or "]->" not in line or not line[-2].isdigit() or not line[-1] == ')':
+        if ": " in line or "]->" not in line or not line[-1] == ')':
             continue
 
-        pattern = re.compile(r"(\w+)@\(([\d\.:]+)\)(\[[^\]]+\])->(?=(\w+)@\(([\d\.:]+)\))")
+        pattern = re.compile(r"(\w+)@\(([a-zA-Z0-9_-]+)\)(\[[^\]]+\])->(?=(\w+)@\(([a-zA-Z0-9_-]+)\))")
         matches = re.finditer(pattern, line)
         previous_dest_host = None
```

**Comment by MegaManSec** [comment]
Closing since I think this is answered.
